### ISSUE TITLE
Startup is blocked if formats is undefined

### ISSUE THREAD

**Issue by PBXg33k** [RealLowMaster/X-Comic-Downloader-Project#3]
I noticed the application wont startup if during startup the files are rescanned.

I am not sure yet what causes this, but it might be caused by the last run being unexpectedly being killed. I've written a dirty hack locally so i could start up again, and the application doesn't seem to need to rescan it again afterwards.

ie: 

- dirty db causes 1.9.9 not to start
- cloned repo and added debug profile locally
- ran cloned repo with patch untill i got my downloaded files
- closed the git instance of app
- ran 1.9.9 and the application seem to work again

If i don't make any sense, my apologies, as i am a bit drunk and it's  2AM, please see my branch for the workaround and if you have any questions, i'll gladly answer https://github.com/powered-by-moe/X-Comic-Downloader-Project/commit/f00a7e34ce2025007fad525f204b08f0ef8e3491

**Comment by RealLowMaster** [comment]
thank you for noticing me from this issue.
I will Try my best to fix it in next version.

**Comment by RealLowMaster** [comment]
it seems this problem will only happened when the comic image length is 1, because I got the same error when my comic have only 1 image sooo i think I know how to fix it.
