### ISSUE TITLE
i installed node.js but i have a problem

### ISSUE THREAD

**Issue by icebr3aker96** [RealLowMaster/X-Comic-Downloader-Project#6]
hi, i was trying to install x comic downloader but when i installed node.js my cmd doesn't recognize the comman "yarn", so i can't run the "yarn install" and "yarn run dist", please help

**Comment by thepaancake** [comment]
i have the same problem pls help

**Comment by RealLowMaster** [comment]
You should install yarn package globally.
To do that:
1. Open CMD.
2. Type: npm i -g yarn
Now you have yarn command supported.
